### ISSUE TITLE
Explain a little

### ISSUE THREAD

**Issue by fghafoor85** [pandhu/wp-amember-login#1]
What happens if the user only had account on amembre and not wordpress?

Does wordpress plugin need to be setup from amember first?

What does this do?
`                 if (count($data->subscriptions) > 0) {
                     // valid subscription id(s), please edit accordingly
                     $paid_subs_id = array(1,2,3,4,7,8,9,42,43,44,45,46,47);
                     $paid_subs_agent = array(1,2,3,4);
                     $paid_subs_reseller = array(7,8,9,42,43,44,45,46,47);
                     //$paid_subs_id = array(32, 33);`

Sorry for so many questions but this might be an awesome plugin if it does what i think it does.

**Comment by pandhu** [comment]
Thankyou for open an issue.

Sorry for messy code, actually im coded this plugin for my own team project. The code you attached is not used.

Currently we have so much limitation.
One of them is when the user only have an account on amember, you need to import it to wordpress.
The other one is we not allowed to map AMember Product to Wordpress Role. 

Im working on this issues right now. I would like to make a new release on Thursday. 
So we dont have to import amember users to wordpress and we can map amember product which user subscribed to wordpress role. 

cheers!

**Comment by fghafoor85** [comment]
Thank you so much for the message! Would love to see the new version. We currently use the wordpress/amember intergeration but it sometimes is buggy and the user get's issues auto logging in to wordpress from amember.

Tested your solution it's very neat!

**Comment by pandhu** [comment]
i just pushed a new version. 
It includes a new setting for role mapping.
You should map aMember Product and Wordpress Role. When user logging in and the user isn't registered yet on wordpress, this plugin will automatically create a new user for that user.

**Comment by fghafoor85** [comment]
I looked at it and it's pretty awesome! 

Does this have potential to cause any login issues with admins, editors login?

**Comment by pandhu** [comment]
the login mechanism is written by this code. and hooked it into [wp_authenticate](https://codex.wordpress.org/Plugin_API/Action_Reference/wp_authenticate)

`if($login_information->ok){
    $user = get_user_by('login', $login_information->login);
    if ( !$user){
	    $user = wp_amember_create_user($login_information);
    } else {
        $user = wp_amember_update_user($login_information);
    }
	wp_amember_login_authenticate_user($user);
}
return;`

if $login_information->ok is false, we will use default wordpress login mechanism.  
So i think it wont trigger any issue with admins and editors login except you have same username for admin in amember. it will bypass wordpress login mechanism.
